Console.Write("Введите номер телефона: ");
int Number = Convert.ToInt32(Console.ReadLine());
int[] array = new int[Number];
int i = array[0];
int a = array[1];
int s = array[2];
int d = array[3];
int f = array[4];
int g = array[5];
int h = array[6];
int j = array[7];
int k = array[8];
int l = array[9];
Console.Write("(" + i + a + s + ")" + d + f + g + "-" + h + j + "-" + k + l + ";");